global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - alert-contact-book.yml

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost: 8090

scrape_configs:
  - job_name: "contact-book"
    static_configs:
    - targets: ["localhost: 8090"]

